[config]
picktype=test
[keys]
; TODO
[weapon]
index = 0
offset = 3032
maxval = 217
[flower]
index = 0
offset = 3257
maxval = 40
[armour]
index = 0
offset = 3297
maxval = 48
[bribe]
index = 0
offset = 3345
maxval = 50
[test]
index = 0
offset = 865
maxval = 18
[output]

[0]
var=0
index=0
x=0
y=0
z=0
