[mszcfg]
; https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
binco = 0x55 ; U
z247 = 0x31 ; 1
dance = 0x30 ; 0
gym = 0x54 ; T
gymcall = 0x33 ; 3
nrg = 0x32 ; 2
endscript = 0xBB ; =
